apiVersion: v1
kind: ConfigMap
metadata:
  name: adot-forwarder-config
  namespace: monitoring
data:
  collector.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318

    processors:
      batch:

    extensions:
      health_check:
        endpoint: 0.0.0.0:13133 # Or any other open port
      pprof:
        endpoint: 0.0.0.0:1777 # Or any other open port
      zpages:
        endpoint: 0.0.0.0:13113 # Or any other open port


    exporters:
      otlphttp/newrelic:
        endpoint: https://otlp.nr-data.net:443
        headers:
          api-key: 64d352987aac450f026acd1c809cef47c1beNRAL

    service:
      extensions: [health_check, pprof, zpages]
      pipelines:
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlphttp/newrelic]