apiVersion: apps/v1
kind: Deployment
metadata:
  name: adot-scraper
  namespace: monitoring
spec:
  replicas: 1   # 2 replicas for HA, AMP will handle deduplication, if there are any, applicable for production, in lower env, we can have only 1 replica #changing it back to
  selector:
    matchLabels:
      app: adot-scraper
  template:
    metadata:
      labels:
        app: adot-scraper
    spec:
      serviceAccountName: adot-sa
      containers:
      - name: adot
        image: public.ecr.aws/aws-observability/aws-otel-collector:latest
        args:
        - --config=/conf/collector.yaml
        ports:
        - containerPort: 8888   # health check
        volumeMounts:
        - name: config
          mountPath: /conf
      volumes:
      - name: config
        configMap:
          name: adot-scraper-config