apiVersion: apps/v1
kind: Deployment
metadata:
  name: alb-traffic-gen
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alb-traffic-gen
  template:
    metadata:
      labels:
        app: alb-traffic-gen
    spec:
      containers:
      - name: curl
        image: curlimages/curl:latest
        command: ["/bin/sh", "-c"]
        args:
        - |
          echo "=== ALB Traffic Generator Started ==="
          while true; do
            echo "=== $(date) ==="
            curl -I -k -m 8 http://vivek-otel-test-lb-1776648454.ap-south-1.elb.amazonaws.com || echo "=== Request Failed ==="
            sleep 3
          done