apiVersion: apps/v1
kind: Deployment
metadata:
  name: yace
  namespace: monitoring
spec:
  replicas: 1   # Removes duplicatoion
  selector:
    matchLabels:
      app: yace
  template:
    metadata:
      labels:
        app: yace
    spec:
      serviceAccountName: yace-sa
      containers:
      - name: yace
        image: quay.io/prometheuscommunity/yet-another-cloudwatch-exporter:v0.65.0
        args:
        - --config.file=/config/config.yaml
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: config
          mountPath: /config

        livenessProbe:
          httpGet:
            path: /metrics
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3

        readinessProbe:
          httpGet:
            path: /metrics
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 3
          
      volumes:
      - name: config
        configMap:
          name: yace-config

      